SMSGateway/Models/Refill_Report.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SMSGateway.Models
{
    public partial class Refill_Report
    {

        public DateTime? fromDate { get; set; }
        public DateTime? toDate { get; set; }

        public List<string> client { get; set; }

    }
}

SMSGateway/Controllers/RefillReportController.cs
using PagedList;
using SMSGateway.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;

namespace SMSGateway.Controllers
{
    public class RefillReportController : Controller
    {
        private SMSGateway_DevEntities db = new SMSGateway_DevEntities();

        public ActionResult _Index()
        {

            ViewBag.Status = new SelectList(db.StatusCodes, "Code", "Description");
            if ((string)Session["code"] == "User")
            {
                ViewBag.Client = new SelectList(db.Clients, "ClientCode", "Name");
            }
            ViewBag.Code = (string)Session["code"];
            return PartialView();

        }
     
        public ActionResult _RefillReport(DateTime? fromDate, DateTime? toDate, string client = null, int pageNumber = 1, int pageSize = 20)
        {
            ViewBag.Client = client;
            ViewBag.FromDate = fromDate;
            ViewBag.ToDate = toDate;
            ViewBag.PageNumber = pageNumber;
            ViewBag.SN = ((pageNumber - 1) * pageSize) + 1;

            ObjectParameter totalPages = new ObjectParameter("pageCount", typeof(int));

            var model = db.spRefillReport(client, fromDate, toDate, pageNumber, totalPages).OrderBy(x => x.CancelledBy).ToList();
            
            
            
            ViewBag.PageCount = totalPages.Value;
            return PartialView(model.ToPagedList(1, pageSize));

        }

        public ActionResult ExportToExcel(Refill_Report formRefill)
        {

            ObjectParameter totalPages = new ObjectParameter("pageCount", typeof(int));
            var pageNumber = 0;
            string clientfilter = null;
            if (formRefill.client != null)
            {
                clientfilter = (formRefill.client.Count() == 0 || formRefill.client == null ? "" : string.Join(",", formRefill.client));
            }
            else
            {
                clientfilter = "";
            }

            var model = db.spRefillReport(clientfilter, formRefill.fromDate, formRefill.toDate, pageNumber, totalPages).OrderBy(x => x.CancelledBy).ToList();

            if (model.Count == 0)
            {
                return PartialView("_NoRecords");

            }
            else
            {

                GridView gv = new GridView() { AutoGenerateColumns = true };


                gv.DataSource = model;

                gv.DataBind();

                Response.ClearContent();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment; filename=Refill_Report.xls");
                Response.ContentType = "application/ms-excel";

                Response.Charset = "";
                StringWriter swriter = new StringWriter();
                HtmlTextWriter htwriter = new HtmlTextWriter(swriter);

                gv.RenderControl(htwriter);

                Response.Output.Write(swriter.ToString());
                Response.Flush();
                Response.End();

                return View();
            }
        }

    }
}

SMSGateway/Views/RefillReport/_Index.cshtml
@model SMSGateway.Models.spRefillReport_Result

@{
    string code = ViewBag.Code;
}
<script>
    $('.datepicker').datepicker({
        orientation: 'bottom',
        autoclose: true,
    })
    $('.clientList').multiselect({
        includeSelectAllOption: true,
        enableCaseInsensitiveFiltering: true,
        enableFiltering: true
    })
</script>

<h2>Refill Report</h2>
<br />

@using (Html.BeginForm("ExportToExcel", "RefillReport", FormMethod.Post))
{
    @*<div class="row form-group activate-filters col-md-12">
        <label>Filter by: </label>
        <br />
        <div class="form-group col-sm-3">
            @if (code == "User")
            {
                <input type="checkbox" class="checkbox-filter-refill client-filter" value="div-client-filter" />
                <text>Client Name</text>
            }
        </div>
        <div class="form-group col-sm-3">
            <input type="checkbox" class="checkbox-filter-refill datetime-filter" value="div-datetime-filter" />
            <text>Date/Time</text>
        </div>
    </div>*@

    <div class="row col-md-12">
        <div class="form-group col-md-1">
            @*@if (code == "User")
            {
                <input type="checkbox" class="checkbox-filter-refill client-filter" value="div-client-filter" />
            }*@
            <label>Client:</label>
        </div>
        <div class="form-group div-client-filter">
            @if (code == "User")
            {
                <div class="col-md-9">
                    @Html.DropDownList("Client", null, new { @class = "form-control clientList", multiple = "multiple" })
                </div>
            }
            else
            {
                @Html.HiddenFor(x => code, new { @class = "clientList" })
            }
        </div>
    </div>

    <div class=" row form-group col-md-12">
        <div class="form-group col-md-1">
            @*<input type="checkbox" class="checkbox-filter-refill datetime-filter" value="div-datetime-filter" />*@
            <label>Date:</label>
        </div>
        <div class="div-datetime-filter">
            <div class="col-md-3" style="width: 115px;">
                <input type="text" name="FromDate" class="form-control datepicker fromDate" placeholder="Date" />
            </div>

            <div class="col-md-1" style="right: 3px; margin: 5px 0 5px 0">
                @Html.Label("to", htmlAttributes: new { @class = "control-label" })
            </div>

            <div class="col-md-3" style="width: 115px;">
                <input type="text" name="ToDate" class="form-control datepicker toDate" placeholder="Date" />
            </div>
        </div>
    </div>


    <div class="form-group col-md-12">
        <input type="button" class="btn btn-warning btnFilter-refill" value="Filter" />
        <input type="submit" class="btn btn-warning btnexport-refillreport" value="Export" formtarget="_blank" />
    </div>
}

<div class="refill-report">
    @{ Html.RenderAction("_RefillReport", "RefillReport"); }
</div>

SMSGateway/Views/RefillReport/_RefillReport.cshtml
@model PagedList.IPagedList<SMSGateway.Models.spRefillReport_Result>
@using PagedList;
@using PagedList.Mvc;
@{
    var pageNumber = ViewBag.PageNumber;
    var totalPages = ViewBag.PageCount;
    DateTime? fromDate = ViewBag.FromDate;
    DateTime? toDate = ViewBag.ToDate;
    string client = ViewBag.Clients;

}
@{
    var i = ViewBag.SN;
   
    var display = "display-none";
    var color = "black";
    
}

<div class="table-container tbl-refill-report">
    <div class="cancelled-purchase-container">
        <input type="checkbox" value="0" class="canceled-purchase-refills" />
        <text><b>  Show canceled purchases</b></text>
    </div>
    <h3>Refill Report</h3>

    @if (Model.Count > 0)
    {
        <table class="table table-striped table-refill">
            <tr>
                <th>SN</th>
                <th>Client Code</th>               
                <th>Client</th>
                <th>Bill No</th>
                <th>SMS Purchased</th>
                <th>Rate</th>
                <th>Amount</th>
                <th>Refill Date</th>
                <th>Refill By</th>
                <th>Remarks</th>
            </tr>
            @foreach (var item in Model)
            {
                if (item.CancelledBy == null)
                {
                    display = "";
                    color = "black";
                }
                else
                {
                    display = "display-none";
                    color = "red";
                }
                <tr refillId="@item.RefillId" class="@display" style="color:@color;">
                    <td>
                        @i
                        @{
                            i = i + 1;
                        }
                    </td>
                    <td>@item.ClientCode</td>
                    <td>@item.Name</td>
                    <td>@item.BillNo</td>
                    <td>@Convert.ToInt32(item.RefillValue)</td>
                    <td>@item.RefillRate</td>
                    <td>@item.RefillAmount</td>
                    <td>@item.RefillDate</td>
                    <td>@item.RefillBy</td>
                    <td>@item.Remarks</td>

                </tr>
            }
        </table>
    }
    else
    {
        <b> There are no current records.</b>
    }
</div>


@if (Model.Count > 0)
{
    <div class="pagination">
        <div class="pre-text">Page </div>
        <button class="btn btn-warning btnPage-refill btnPrevPage"><i class="fa fa-chevron-left"></i></button>
        <input type="text" value="@pageNumber" class="txtPageNo-refill" />
        @Html.HiddenFor(x => totalPages)
        <button class="btn btn-warning btnPage-refill btnNextPage"><i class="fa fa-chevron-right"></i></button>
        <div class="post-text"> of @totalPages</div>
    </div>
    <div class="pagination-message-refill text-danger">

    </div>
    @Html.HiddenFor(x => fromDate)
    @Html.HiddenFor(x => toDate)
    @Html.HiddenFor(x => client)
}