SMSGateway/Controllers/ConsumerController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using SMSGateway.Models;

namespace SMSGateway.Controllers
{
    public class ConsumerController : Controller
    {
        private SMSGateway_DevEntities db = new SMSGateway_DevEntities();
        SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["ADO_connection"].ConnectionString);

        public ActionResult _Index()
        {
            var clients = db.Clients.ToList();
            SelectList clt = new SelectList(clients, "ClientCode", "Name");
            ViewBag.Client = clt;
            //ViewBag.Client = new SelectList(db.Clients, "ClientCode", "Name");
            ViewBag.Code = (string)Session["code"];
            return PartialView();
        }

        public ActionResult _ConsumerReport(string clientCode, string clientType, DateTime? fromDate, DateTime? toDate, int rows = 50)
        {
            SqlCommand command = new SqlCommand("spSMSClientConsumptionAll", connection);
            command.CommandTimeout = 600;
            connection.Open();
    
            command.CommandType = CommandType.StoredProcedure;
            if (fromDate == null)
            {
                command.Parameters.Add("@FromDate", SqlDbType.DateTime).Value = DBNull.Value;
            }
            else
            {
                command.Parameters.AddWithValue("@FromDate", fromDate);
            }

            if (toDate == null)
            {
                command.Parameters.Add("@ToDate", SqlDbType.DateTime).Value = DBNull.Value;
            }
            else
            {
                command.Parameters.AddWithValue("@ToDate", toDate);
            }

            command.Parameters.AddWithValue("@ClientCode", clientCode);
            command.Parameters.AddWithValue("@ClientType", clientType);

            command.CommandText = "spSMSClientConsumptionAll"; //store procedure name

            command.Parameters.Add("@TotalOpeningBalanceCredit", SqlDbType.Int);
            command.Parameters["@TotalOpeningBalanceCredit"].Direction = ParameterDirection.Output;

            command.Parameters.Add("@TotalOpeningBalanceAmt", SqlDbType.Int);
            command.Parameters["@TotalOpeningBalanceAmt"].Direction = ParameterDirection.Output;

            command.Parameters.Add("@TotalPurchaseCredit", SqlDbType.Int);
            command.Parameters["@TotalPurchaseCredit"].Direction = ParameterDirection.Output;

            command.Parameters.Add("@TotalPurchaseAmt", SqlDbType.Int);
            command.Parameters["@TotalPurchaseAmt"].Direction = ParameterDirection.Output;

            command.Parameters.Add("@TotalConsumedCredit", SqlDbType.Int);
            command.Parameters["@TotalConsumedCredit"].Direction = ParameterDirection.Output;

            command.Parameters.Add("@TotalConsumedAmt", SqlDbType.Int);
            command.Parameters["@TotalConsumedAmt"].Direction = ParameterDirection.Output;

            command.Parameters.Add("@TotalClosingBalanceCredit", SqlDbType.Int);
            command.Parameters["@TotalClosingBalanceCredit"].Direction = ParameterDirection.Output;

            command.Parameters.Add("@TotalClosingBalanceAmt", SqlDbType.Int);
            command.Parameters["@TotalClosingBalanceAmt"].Direction = ParameterDirection.Output;


            SqlDataAdapter da = new SqlDataAdapter(command);
            da.SelectCommand = command;
            DataSet ds = new DataSet();
            da.Fill(ds);
            command.ExecuteNonQuery();
            connection.Close();

            List<SMSClientAll> consumerlist = new List<SMSClientAll>();

            if (ds != null && ds.Tables.Count > 0)
            {
                foreach (DataRow item in ds.Tables[0].Rows)
                {
                    SMSClientAll c = new SMSClientAll();
                    c.ClientCode = item["ClientCode"].ToString();
                    c.ClientName = item["ClientName"].ToString();
                    c.OpeningBalanceCredit = Convert.ToDecimal(item["OpeningBalanceCredit"]);
                    c.OpeningBalanceAmt = Convert.ToDecimal(item["OpeningBalanceAmt"]);
                    c.PurchaseCredit = Convert.ToDecimal(item["PurchaseCredit"]);
                    c.PurchaseAmount = Convert.ToDecimal(item["PurchaseAmount"]);
                    c.ConsumedCredit = Convert.ToDecimal(item["ConsumedCredit"]);
                    c.ConsumedAmt = Convert.ToDecimal(item["ConsumedAmt"]);
                    c.ClosingBalanceCredit = Convert.ToDecimal(item["ClosingBalanceCredit"]);
                    c.ClosingBalanceAmt = Convert.ToDecimal(item["ClosingBalanceAmt"]);

                    consumerlist.Add(c);
                };
            }
            try
            {
                connection.Open();
                command.ExecuteNonQuery();

                var openingbalancecredit = Convert.ToDecimal(command.Parameters["@TotalOpeningBalanceCredit"].Value);
                ViewBag.TotalOpeningBalanceCredit = openingbalancecredit;

                var openingbalanceamount = Convert.ToDecimal(command.Parameters["@TotalOpeningBalanceAmt"].Value);
                ViewBag.TotalOpeningBalanceAmt = openingbalanceamount;

                var purchasecredit = Convert.ToDecimal(command.Parameters["@TotalPurchaseCredit"].Value);
                ViewBag.TotalPurchaseCredit = purchasecredit;

                var purchaseamount = Convert.ToDecimal(command.Parameters["@TotalPurchaseAmt"].Value);
                ViewBag.TotalPurchaseAmount = purchaseamount;

                var consumedcredit = Convert.ToDecimal(command.Parameters["@TotalConsumedCredit"].Value);
                ViewBag.TotalConsumedCredit = consumedcredit;

                var consumedamt = Convert.ToDecimal(command.Parameters["@TotalConsumedAmt"].Value);
                ViewBag.TotalConsumedAmt = consumedamt;

                var closingbalancecredit = Convert.ToDecimal(command.Parameters["@TotalOpeningBalanceCredit"].Value);
                ViewBag.TotalClosingBalanceCredit = closingbalancecredit;

                var closingbalanceamount = Convert.ToDecimal(command.Parameters["@TotalOpeningBalanceAmt"].Value);
                ViewBag.TotalClosingBalanceAmt = closingbalanceamount;
            }
            catch (Exception ex)
            {
                throw ex;
            }

            ViewBag.SelectedRows = rows;

            return PartialView(consumerlist);
        }

    }
}

SMSGateway/Views/Consumer/_ConsumerReport.cshtml
@model List<SMSGateway.Models.SMSClientAll>

@{
    var totalOpeningBalanceCredit = ViewBag.TotalOpeningBalanceCredit;
    var totalOpeningBalanceAmt = ViewBag.TotalOpeningBalanceAmt;
    var totalPurchaseCredit = ViewBag.TotalPurchaseCredit;
    var totalPurchaseAmount = ViewBag.TotalPurchaseAmount;
    var totalConsumedCredit = ViewBag.TotalConsumedCredit;
    var totalConsumedAmt = ViewBag.TotalConsumedAmt;
    var totalClosingBalanceCredit = ViewBag.TotalClosingBalanceCredit;
    var totalClosingBalanceAmt = ViewBag.TotalClosingBalanceAmt;
    var totalRows = ViewBag.TotalRows;
    var selectedRows = ViewBag.SelectedRows;

}
<br />
<hr />


<div class="form-horizontal col-md-12">
    <div class="form-group">
        <div class="col-md-3 bg-red">
            <!-- small box -->
            <div class="small-box">
                <div class="inner col-md-12 text-center">
                    <h4><b>Total Opening Balance</b></h4>
                    <div class="inner col-md-6">
                        <h4 class="text-bold">@totalOpeningBalanceAmt</h4>
                        <p class="text-bold">Amount</p>
                    </div>
                    <div class="inner col-md-6">
                        <h4 class="text-bold">@totalOpeningBalanceCredit</h4>
                        <p class="text-bold">Credit</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-card"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-3 bg-green">
            <!-- small box -->
            <div class="small-box">
                <div class="inner col-md-12 text-center">
                    <h4><b>Total Purchase</b></h4>
                            <div class="inner col-md-6">
                                <h4 class="text-bold">@totalPurchaseAmount</h4>
                                <p class="text-bold">Amount</p>
                            </div>
                            <div class="inner col-md-6">
                                <h4 class="text-bold">@totalPurchaseCredit</h4>
                                <p class="text-bold">Credit</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-pricetag"></i>
                            </div>
                </div>
            </div>
        </div>

        <div class="col-md-3  bg-yellow">
            <!-- small box -->
            <div class="small-box">
                <div class="inner col-md-12 text-center">
                    <h4><b>Total Consumed</b></h4>
                    <div class="inner col-md-6">
                        <h4 class="text-bold">@totalConsumedAmt</h4>
                        <p class="text-bold">Amount</p>
                    </div>
                    <div class="inner col-md-6">
                        <h4 class="text-bold">@totalConsumedCredit</h4>
                        <p class="text-bold">Credit</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-social-usd"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-3  bg-aqua">
            <!-- small box -->
            <div class="small-box">
                <div class="inner col-md-12 text-center">
                    <h4><b>Total Closing Balance</b></h4>
                    <div class="inner col-md-6">
                        <h4 class="text-bold">@totalClosingBalanceAmt</h4>
                        <p class="text-bold">Amount</p>
                    </div>
                    <div class="inner col-md-6">
                        <h4 class="text-bold">@totalClosingBalanceCredit</h4>
                        <p class="text-bold">Credit</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-cash"></i>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="table-container">
    @if (Model.Count > 0)
     {
        <table class="table table-striped table-consumer-report">
            <tr>
                <th class="th-client-code">Client Code</th>
                <th class="th-client-name">Client Name</th>
                <th class="th-opening-balance-credit">Opening Balance(Credit)</th>
                <th class="th-opening-balance-amt">Opening Balance(Amount)</th>
                <th class="th-purchase-credit">Purchase(Credit)</th>
                <th class="th-purchase-amount">Purchase(Amount)</th>
                <th class="th-consumed-credit">Consumed(Credit)</th>
                <th class="th-consumed-amt">Consumed(Amount)</th>
                <th class="th-closing-balance-credit">Closing Balance(Credit)</th>
                <th class="th-closing-balance-amt">Closing Balance(Amount)</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="td-client-code">@item.ClientCode</td>
                    <td class="td-client-name">@item.ClientName</td>
                    <td class="td-opening-balance-credit">@item.OpeningBalanceCredit </td>
                    <td class="td-opening-balance-amt">@item.OpeningBalanceAmt</td>
                    <td class="td-purchase-credit">@item.PurchaseCredit</td>
                    <td class="td-purchase-amount">@item.PurchaseAmount</td>
                    <td class="td-consumed-credit">@item.ConsumedCredit</td>
                    <td class="td-consumed-amt">@item.ConsumedAmt</td>
                    <td class="td-closing-balance-credit">@item.ClosingBalanceCredit </td>
                    <td class="td-closing-balance-amt">@item.ClosingBalanceAmt</td>
                </tr>
             }
            @if (totalRows > selectedRows)
                {
                <tr>
                    <td class="td-load-more" colspan="10">Load More</td>
                </tr>
                }
        </table>
     }

    else
    {
        <b>No records could be found</b>
    }
</div>

SMSGateway/Views/Consumer/_Index.cshtml
@model SMSGateway.Models.SMSClientAll
@{
    string code = ViewBag.Code;
}
<h2>Consumer Report</h2>
<br />

<script>
    $('.datepicker').datepicker({
        orientation: 'bottom',
        autoclose: true,
    })

    $('.client-list').multiselect({
        includeSelectAllOption: true,
        enableCaseInsensitiveFiltering: true,
        enableFiltering: true
    })
</script>

<div class="form-horizontal filters">

    @using (Html.BeginForm("_ConsumerReport", "Consumer", FormMethod.Post))
     {
        <div class="form-group">
           @* @if (code == "User")
            {
                <div class="div-client-filter col-md-4">
                    <fieldset>

                        <legend class="form-group col-md-12">
                            Client
                        </legend>

                        <div class="form-group col-md-12">

                            @Html.DropDownList("client", ViewBag.Client as SelectList, "All", new { @class = "form-control client-list" })

                            <br />
                        </div>

                        <legend class="form-group col-md-12">
                            Client Type
                        </legend>

                        <div class="col-md-8">
                            @Html.DropDownListFor(x => x.ClientType, new List<SelectListItem>
                                {
                                    new SelectListItem{Text="All", Value="A"},
                                    new SelectListItem{Text="Clients", Value="C"},
                                    new SelectListItem{Text="Non-Clients", Value ="N" }
                                }
                                , new { @class = "form-control clientType" })
                        </div>

                    </fieldset>
                </div>
            }
            <div class="div-datetime-filter col-md-4">
                <fieldset>
                    <legend class="form-group col-md-12">
                        Date/Time
                    </legend>
                    <div class="form-group col-md-12">
                        @Html.Label("From: ", htmlAttributes: new { @class = "control-label" })<br />
                        <div class="col-md-12">
                            @*<input type="text" class="form-control datepicker fromDate" placeholder="Date" />
                            @Html.EditorFor(x => x.FromDate, new { htmlAttributes = new { @class = "form-control datepicker fromDate", @placeholder = "Date" } })
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        @Html.Label("To: ", htmlAttributes: new { @class = "control-label" })<br />
                        <div class="col-md-12">
                            @*<input type="text" class="form-control datepicker toDate" placeholder="Date" />
                            @Html.EditorFor(x => x.ToDate, new { htmlAttributes = new { @class = "form-control datepicker toDate", @placeholder = "Date" } })
                        </div>
                    </div>

                </fieldset>
            </div>*@



                @if (code == "User")
                {
                    <div class="form-group col-md-12">
                        <div class="col-md-2">
                            <label>Client:</label>
                        </div>

                        <div class="col-md-10">
                            @Html.DropDownList("client", ViewBag.Client as SelectList, "All", new { @class = "form-control client-list" })
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-2">
                            <label>Client Type:</label>
                        </div>
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.ClientType, new List<SelectListItem>
                                {
                                    new SelectListItem{Text="All", Value="A"},
                                    new SelectListItem{Text="Clients", Value="C"},
                                    new SelectListItem{Text="Non-Clients", Value ="N" }
                                }
                                , new { @class = "form-control clientType", style="width: 112px;"})
                        </div>
                    </div>
                }

            <div class="form-group col-md-12" style="width: 50%;">
                <div class="col-md-4">
                    <label>Date:</label>
                </div>
                <div style="right: 100px;">
                    <div class="col-md-3" style="left: 5px; width: 115px;">
                        @Html.EditorFor(x => x.FromDate, new { htmlAttributes = new { @class = "form-control datepicker fromDate", @Value = DateTime.Now.ToString("yyyy-MM-dd") } })
                    </div>
                    <div class="col-md-1" style="left: 7px; margin-top:-5px; margin-bottom: 5px;">
                        @Html.Label("to", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-3" style="left: 5px;  width: 115px;">
                        @Html.EditorFor(x => x.ToDate, new { htmlAttributes = new { @class = "form-control datepicker toDate", @Value = DateTime.Now.ToString("yyyy-MM-dd") } })
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <input type="button" class="btn btn-warning btnGenerateReport" value="Generate Report" />
            </div>
        </div>
     }

   
</div>

<div class="consumer">

</div>